name: Trigger auto deployment for test999

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/test999-AutoDeployTrigger-0afe47bc-cae7-4b4c-9b27-2627d0682644.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: testacrtask.azurecr.io
          username: ${{ secrets.TEST999_REGISTRY_USERNAME }}
          password: ${{ secrets.TEST999_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: testacrtask.azurecr.io/test999:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TEST999_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n test999 -g TESTACRTASK --server testacrtask.azurecr.io --username  ${{ secrets.TEST999_REGISTRY_USERNAME }} --password ${{ secrets.TEST999_REGISTRY_PASSWORD }}
            az containerapp update -n test999 -g TESTACRTASK --image testacrtask.azurecr.io/test999:${{ github.sha }}
